#!/bin/sh
# SDLC service wiring CLI (POSIX shell — macOS & Linux, no install required).
#
# Run it from inside a NEW service folder created under this project's workspace/, e.g.:
#   cd workspace/services/payments-api
#   sh ../../.sdlc/sdlc.sh init --name payments-api --type backend
#   sh ../../.sdlc/sdlc.sh init --name gateway            # --type defaults to "all"
#   sh ../../.sdlc/sdlc.sh sync                            # after a framework/governance change
#
# --type is one of: all (default) | backend | frontend | data | infra.  "all" imports every governance
# folder; the others import only the standards relevant to that service type.
#
# What `init` does (idempotent): finds the project root via the `.sdlc-root` marker, writes/updates this
# service's CLAUDE.md managed "Project context" block (@imports governance + requirements/design), writes
# .claude/settings.json enabling the `sdlc` plugin, writes .sdlc/service.json (the durable link record),
# and best-effort installs the framework plugin via the `claude` CLI when present.

set -eu

PLUGIN='sdlc@sdlc-hub'
MARKETPLACE='sdlc-hub'
START='<!-- sdlc:start (managed — do not edit; regenerated by `sdlc sync`) -->'
END='<!-- sdlc:end -->'
NL='
'

# ---- parse args: first positional is the command; --name / --type carry values ----
cmd='init'; argName=''; argType=''
while [ $# -gt 0 ]; do
  case "$1" in
    --name) argName=${2:-}; shift; [ $# -gt 0 ] && shift ;;
    --type) argType=${2:-}; shift; [ $# -gt 0 ] && shift ;;
    init|sync|INIT|SYNC) cmd=$1; shift ;;
    *) shift ;;
  esac
done
cmd=$(printf '%s' "$cmd" | tr '[:upper:]' '[:lower:]')
if [ "$cmd" != 'init' ] && [ "$cmd" != 'sync' ]; then
  echo "Unknown command \"$cmd\". Use: init | sync" >&2; exit 1
fi

serviceDir=$(pwd -P)

# ---- find the project root by walking up to the .sdlc-root marker ----
find_root() {
  d=$1
  while :; do
    [ -f "$d/.sdlc-root" ] && { printf '%s\n' "$d"; return 0; }
    parent=$(dirname "$d")
    [ "$parent" = "$d" ] && return 1
    d=$parent
  done
}
if ! root=$(find_root "$serviceDir"); then
  echo "x No .sdlc-root marker found above this folder." >&2
  echo "  Run this from inside a service folder nested under the project's workspace/." >&2
  exit 1
fi

# ---- read the marker (flat platform-generated JSON; extract the three fields we use) ----
json_val() { sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$2" | head -n1; }
project=$(json_val project "$root/.sdlc-root")
infoName=$(json_val name "$root/.sdlc-root")
frameworkPin=$(json_val frameworkVersion "$root/.sdlc-root"); [ -n "$frameworkPin" ] || frameworkPin='local'

type=$argType; [ -n "$type" ] || type='all'
type=$(printf '%s' "$type" | tr '[:upper:]' '[:lower:]')
name=$argName; [ -n "$name" ] || name=$(basename "$serviceDir")

# ---- portable relative path from $1 (dir) to $2, forward-slashed, './'-prefixed unless dotted ----
relpath() {
  src=${1%/}; dst=${2%/}
  [ -n "$src" ] || src='/'
  [ -n "$dst" ] || dst='/'
  common=$src; up=''
  while :; do
    case "$dst/" in "$common"/*) break ;; esac
    up="../$up"
    [ "$common" = '/' ] && break
    common=$(dirname "$common")
  done
  if [ "$common" = '/' ]; then forward=${dst#/}; else forward=${dst#"$common"/}; [ "$forward" = "$dst" ] && forward=''; fi
  up=${up%/}
  if [ -z "$up" ] && [ -z "$forward" ]; then rel='.'
  elif [ -z "$up" ]; then rel=$forward
  elif [ -z "$forward" ]; then rel=$up
  else rel="$up/$forward"; fi
  case "$rel" in .*) : ;; *) rel="./$rel" ;; esac
  printf '%s\n' "$rel"
}

jesc() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

# ---- governance folders for this type ----
if [ "$type" = 'all' ]; then
  if [ -d "$root/governance" ]; then
    govFolders=$(find "$root/governance" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | LC_ALL=C sort)
  else govFolders=''; fi
else
  case "$type" in
    backend)  govFolders='backend architecture security devops qa' ;;
    frontend) govFolders='frontend architecture qa' ;;
    data)     govFolders='backend architecture security qa' ;;
    infra)    govFolders='devops security architecture release' ;;
    *)        govFolders='architecture qa' ;;
  esac
fi

# ---- collect governance + artifact imports that actually exist ----
govImports=''
for f in $govFolders; do
  gdir="$root/governance/$f"
  [ -d "$gdir" ] || continue
  while IFS= read -r file; do
    [ -n "$file" ] || continue
    govImports="${govImports}- @$(relpath "$serviceDir" "$file")${NL}"
  done <<EOF
$(find "$gdir" -type f -iname '*.md' | LC_ALL=C sort)
EOF
done
govImports=$(printf '%s' "$govImports")

artImports=''
for a in 'artifacts/lifecycle/02-business-analysis/brd.md' 'artifacts/lifecycle/03-requirements/prd.md' 'artifacts/lifecycle/04-architecture/hld.md'; do
  [ -f "$root/$a" ] && artImports="${artImports}- @$(relpath "$serviceDir" "$root/$a")${NL}"
done
artImports=$(printf '%s' "$artImports")

processGuide=''
[ -f "$root/framework/PROCESS_GUIDE.md" ] && processGuide=$(relpath "$serviceDir" "$root/framework/PROCESS_GUIDE.md")

# ---- build the managed CLAUDE.md block ----
block="$START$NL"
block="${block}## Project context — $project ($infoName)$NL"
block="$block$NL"
block="${block}This is the **$name** service (type: \`$type\`) in project **$project**. It must follow the$NL"
block="${block}project framework and governance below. Treat these as binding standards for everything you build here.$NL"
block="$block$NL"
block="${block}### Framework tooling$NL"
block="${block}Skills, agents, commands, gates, and schemas come from the **sdlc** Claude Code plugin$NL"
block="${block}(enabled via \`.claude/settings.json\`). Use them for drafting, reviews, and gate checks.$NL"
[ -n "$processGuide" ] && block="${block}${NL}Process guide: @$processGuide$NL"
block="$block$NL"
block="${block}### Governance standards (must follow)$NL"
if [ -n "$govImports" ]; then block="${block}${govImports}$NL"; else block="${block}_(no governance files found for this service type yet)_$NL"; fi
block="$block$NL"
block="${block}### Requirements & design this service implements$NL"
if [ -n "$artImports" ]; then block="${block}${artImports}$NL"; else block="${block}_(no requirements/design artifacts published yet — run again after they exist)_$NL"; fi
block="${block}$END"

# ---- write CLAUDE.md (create with a starter header, or replace only the managed block) ----
claudePath="$serviceDir/CLAUDE.md"
if [ -f "$claudePath" ]; then
  if grep -qF "$START" "$claudePath" && grep -qF "$END" "$claudePath"; then
    claude=$(START="$START" END="$END" BLOCK="$block" awk '
      BEGIN{ s=ENVIRON["START"]; e=ENVIRON["END"]; b=ENVIRON["BLOCK"]; inb=0; done=0 }
      { if (!done && $0==s) { print b; inb=1; done=1; next }
        if (inb) { if ($0==e) inb=0; next }
        print }' "$claudePath")
  else
    cur=$(cat "$claudePath")
    claude="$cur$NL$NL$block"
  fi
else
  claude="# $name$NL$NL> Service overview: run \`/init\` inside Claude Code to flesh this out.$NL$NL$block"
fi
mkdir -p "$(dirname "$claudePath")"
printf '%s\n' "$claude" > "$claudePath"

# ---- .claude/settings.json: enable the framework plugin ----
settingsPath="$serviceDir/.claude/settings.json"
mkdir -p "$serviceDir/.claude"
if [ ! -f "$settingsPath" ]; then
  printf '%s\n' '{
  "enabledPlugins": {
    "sdlc@sdlc-hub": true
  }
}' > "$settingsPath"
elif grep -qF '"sdlc@sdlc-hub"' "$settingsPath"; then
  : # already enabled
elif command -v jq >/dev/null 2>&1; then
  merged=$(jq '.enabledPlugins["sdlc@sdlc-hub"]=true' "$settingsPath")
  printf '%s\n' "$merged" > "$settingsPath"
else
  SETTINGS_WARN=1
fi

# ---- .sdlc/service.json: the durable link record ----
gf=''; sep=''
for f in $govFolders; do gf="$gf$sep    \"$(jesc "$f")\""; sep=",$NL"; done
if [ -z "$gf" ]; then gfBlock='[]'; else gfBlock="[$NL$gf$NL  ]"; fi
projectRootRel=$(relpath "$serviceDir" "$root"); projectRootRel=${projectRootRel%/}
mkdir -p "$serviceDir/.sdlc"
printf '%s\n' "{
  \"schema\": 1,
  \"project\": \"$(jesc "$project")\",
  \"service\": \"$(jesc "$name")\",
  \"type\": \"$(jesc "$type")\",
  \"frameworkPlugin\": \"$PLUGIN\",
  \"frameworkPin\": \"$(jesc "$frameworkPin")\",
  \"projectRootRel\": \"$(jesc "$projectRootRel")\",
  \"governanceFolders\": $gfBlock
}" > "$serviceDir/.sdlc/service.json"

# ---- best-effort plugin registration/install via the claude CLI ----
marketplace=$(relpath "$serviceDir" "$root/.claude-plugin/marketplace.json")
claudeOk=0
if command -v claude >/dev/null 2>&1; then
  claudeOk=1
  if [ "$cmd" = 'sync' ]; then
    claude plugin marketplace update "$MARKETPLACE" || echo "  (skipped) claude plugin marketplace update $MARKETPLACE"
    claude plugin update "$PLUGIN" --scope user --yes || echo "  (skipped) claude plugin update $PLUGIN"
  else
    claude plugin marketplace add "$marketplace" || echo "  (skipped) claude plugin marketplace add $marketplace"
    claude plugin install "$PLUGIN" --scope user --yes || echo "  (skipped) claude plugin install $PLUGIN"
  fi
fi

# ---- summary ----
verb='Wired'; [ "$cmd" = 'sync' ] && verb='Synced'
govCount=$(printf '%s' "$govImports" | grep -c '^- @' || true)
artCount=$(printf '%s' "$artImports" | grep -c '^- @' || true)
echo ""
echo "OK $verb service \"$name\" ($type) to project $project"
echo "  - CLAUDE.md            — $govCount governance file(s) + $artCount artifact(s) imported"
echo "  - .claude/settings.json — sdlc plugin enabled"
echo "  - .sdlc/service.json    — link record written"
if [ "${SETTINGS_WARN:-0}" = '1' ]; then
  echo ""
  echo "  ! Could not safely merge an existing .claude/settings.json without jq."
  echo "    Add this key yourself:  \"enabledPlugins\": { \"sdlc@sdlc-hub\": true }"
fi
if [ "$claudeOk" = '0' ]; then
  echo ""
  echo "  The \`claude\` CLI was not found, so the framework plugin was not installed automatically."
  echo "  Once Claude Code is installed, run from this folder:"
  echo "    claude plugin marketplace add $marketplace"
  echo "    claude plugin install $PLUGIN --scope user --yes"
fi
echo ""
echo "  Next: open Claude Code here and run \`/init\` to complete the service overview."
echo ""
