#Requires -Version 5.1
<#
  SDLC service wiring CLI (Windows PowerShell — no install required).

  Run it from inside a NEW service folder created under this project's workspace/, e.g.:
    cd workspace\services\payments-api
    powershell -ExecutionPolicy Bypass -File ..\..\.sdlc\sdlc.ps1 init -Name payments-api -Type backend
    powershell -ExecutionPolicy Bypass -File ..\..\.sdlc\sdlc.ps1 init -Name gateway          # -Type defaults to "all"
    powershell -ExecutionPolicy Bypass -File ..\..\.sdlc\sdlc.ps1 sync                          # after a framework/governance change

  -Type is one of: all (default) | backend | frontend | data | infra. "all" imports every governance
  folder; the others import only the standards relevant to that service type.

  What `init` does (idempotent):
    1. Finds the project root by walking up to the `.sdlc-root` marker.
    2. Writes/updates this service's CLAUDE.md with a managed "Project context" block that @imports the
       governance standards for the service TYPE plus the project's requirements/design artifacts.
    3. Writes .claude\settings.json enabling the `sdlc` Claude Code plugin.
    4. Writes .sdlc\service.json (the durable link record + framework pin).
    5. Best-effort registers + installs the framework plugin via the `claude` CLI (if present).
#>
param(
  [string]$Command = 'init',
  [string]$Name,
  [string]$Type
)

$ErrorActionPreference = 'Stop'

$PLUGIN = 'sdlc@sdlc-hub'
$MARKETPLACE = 'sdlc-hub'
$EMDASH = [char]0x2014
$GOVERNANCE_BY_TYPE = @{
  backend  = @('backend', 'architecture', 'security', 'devops', 'qa')
  frontend = @('frontend', 'architecture', 'qa')
  data     = @('backend', 'architecture', 'security', 'qa')
  infra    = @('devops', 'security', 'architecture', 'release')
  default  = @('architecture', 'qa')
}
$ARTIFACTS = @(
  'artifacts/lifecycle/02-business-analysis/brd.md',
  'artifacts/lifecycle/03-requirements/prd.md',
  'artifacts/lifecycle/04-architecture/hld.md'
)
$START = '<!-- sdlc:start (managed ' + $EMDASH + ' do not edit; regenerated by `sdlc sync`) -->'
$END   = '<!-- sdlc:end -->'

function Write-Utf8($path, $text) {
  $dir = Split-Path -Parent $path
  if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding $false))
}

function Get-RelPath($from, $to) {
  # Relative path from $from to $to, forward-slashed, './'-prefixed unless already dotted. No existence needed.
  $from = [System.IO.Path]::GetFullPath($from).TrimEnd('\', '/')
  $to   = [System.IO.Path]::GetFullPath($to).TrimEnd('\', '/')
  $fs = $from -split '[\\/]+'
  $ts = $to   -split '[\\/]+'
  $i = 0
  while ($i -lt $fs.Count -and $i -lt $ts.Count -and $fs[$i] -ieq $ts[$i]) { $i++ }
  $parts = @()
  for ($j = $i; $j -lt $fs.Count; $j++) { $parts += '..' }
  for ($j = $i; $j -lt $ts.Count; $j++) { $parts += $ts[$j] }
  if ($parts.Count -eq 0) { return '.' }
  $r = ($parts -join '/')
  if ($r -notmatch '^\.') { $r = './' + $r }
  return $r
}

function Find-Root($start) {
  $dir = [System.IO.Path]::GetFullPath($start)
  while ($true) {
    if (Test-Path (Join-Path $dir '.sdlc-root')) { return $dir }
    $parent = Split-Path -Parent $dir
    if (-not $parent -or $parent -eq $dir) { return $null }
    $dir = $parent
  }
}

function Get-JsonEsc($s) { return (($s -replace '\\', '\\') -replace '"', '\"') }

function Invoke-Best($cmd) {
  try { Invoke-Expression $cmd | Out-Null } catch { Write-Host "  (skipped) $cmd" }
}

# ---- resolve command / paths ----
$cmd = $Command.ToLower()
if ($cmd -ne 'init' -and $cmd -ne 'sync') { Write-Error "Unknown command `"$cmd`". Use: init | sync"; exit 1 }

$serviceDir = (Get-Location).Path
$root = Find-Root $serviceDir
if (-not $root) {
  Write-Host "x No .sdlc-root marker found above this folder."
  Write-Host "  Run this from inside a service folder nested under the project's workspace/."
  exit 1
}
$info = Get-Content (Join-Path $root '.sdlc-root') -Raw -Encoding UTF8 | ConvertFrom-Json
$type = if ($Type) { $Type } else { 'all' }
$type = $type.ToLower()
$name = if ($Name) { $Name } else { Split-Path -Leaf $serviceDir }
$frameworkPin = if ($info.frameworkVersion) { $info.frameworkVersion } else { 'local' }
$infoName = if ($info.name) { $info.name } else { '' }

# ---- governance folders for this type ----
if ($type -eq 'all') {
  $gdir = Join-Path $root 'governance'
  $govFolders = if (Test-Path $gdir) { (Get-ChildItem -Path $gdir -Directory | Sort-Object Name | ForEach-Object { $_.Name }) } else { @() }
} else {
  $govFolders = if ($GOVERNANCE_BY_TYPE.ContainsKey($type)) { $GOVERNANCE_BY_TYPE[$type] } else { $GOVERNANCE_BY_TYPE['default'] }
}
$govFolders = @($govFolders)

# ---- collect governance + artifact imports that actually exist ----
$govImports = @()
foreach ($f in $govFolders) {
  $fdir = Join-Path (Join-Path $root 'governance') $f
  if (Test-Path $fdir) {
    Get-ChildItem -Path $fdir -Recurse -File -Filter *.md | Sort-Object FullName | ForEach-Object {
      $govImports += (Get-RelPath $serviceDir $_.FullName)
    }
  }
}
$artImports = @()
foreach ($a in $ARTIFACTS) {
  $ap = Join-Path $root $a
  if (Test-Path $ap) { $artImports += (Get-RelPath $serviceDir $ap) }
}
$pgPath = Join-Path $root 'framework/PROCESS_GUIDE.md'
$processGuide = if (Test-Path $pgPath) { Get-RelPath $serviceDir $pgPath } else { $null }

# ---- build the managed CLAUDE.md block ----
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add($START)
$lines.Add(("## Project context " + $EMDASH + " $($info.project) ($infoName)").TrimEnd())
$lines.Add('')
$lines.Add("This is the **$name** service (type: ``$type``) in project **$($info.project)**. It must follow the")
$lines.Add('project framework and governance below. Treat these as binding standards for everything you build here.')
$lines.Add('')
$lines.Add('### Framework tooling')
$lines.Add('Skills, agents, commands, gates, and schemas come from the **sdlc** Claude Code plugin')
$lines.Add('(enabled via `.claude/settings.json`). Use them for drafting, reviews, and gate checks.')
if ($processGuide) { $lines.Add("`nProcess guide: @$processGuide") } else { $lines.Add('') }
$lines.Add('')
$lines.Add('### Governance standards (must follow)')
if ($govImports.Count) { $lines.Add((($govImports | ForEach-Object { "- @$_" }) -join "`n")) }
else { $lines.Add('_(no governance files found for this service type yet)_') }
$lines.Add('')
$lines.Add('### Requirements & design this service implements')
if ($artImports.Count) { $lines.Add((($artImports | ForEach-Object { "- @$_" }) -join "`n")) }
else { $lines.Add("_(no requirements/design artifacts published yet " + $EMDASH + " run again after they exist)_") }
$lines.Add($END)
$block = ($lines -join "`n")

# ---- write CLAUDE.md (create with a starter header, or replace only the managed block) ----
$claudePath = Join-Path $serviceDir 'CLAUDE.md'
if (Test-Path $claudePath) {
  $cur = Get-Content $claudePath -Raw -Encoding UTF8
  $si = $cur.IndexOf($START, [System.StringComparison]::Ordinal)
  $ei = $cur.IndexOf($END, [System.StringComparison]::Ordinal)
  if ($si -ge 0 -and $ei -ge 0) {
    $claude = $cur.Substring(0, $si) + $block + $cur.Substring($ei + $END.Length)
  } else {
    $claude = $cur.TrimEnd() + "`n`n" + $block + "`n"
  }
} else {
  $claude = "# $name`n`n> Service overview: run ``/init`` inside Claude Code to flesh this out.`n`n$block`n"
}
Write-Utf8 $claudePath $claude

# ---- .claude/settings.json: enable the framework plugin ----
$settingsPath = Join-Path $serviceDir '.claude/settings.json'
$settings = if (Test-Path $settingsPath) { Get-Content $settingsPath -Raw -Encoding UTF8 | ConvertFrom-Json } else { [pscustomobject]@{} }
if (($settings.PSObject.Properties.Name -contains 'enabledPlugins') -and $settings.enabledPlugins) {
  $settings.enabledPlugins | Add-Member -NotePropertyName $PLUGIN -NotePropertyValue $true -Force
} else {
  $settings | Add-Member -NotePropertyName 'enabledPlugins' -NotePropertyValue ([pscustomobject]@{ $PLUGIN = $true }) -Force
}
Write-Utf8 $settingsPath ((($settings | ConvertTo-Json -Depth 20)) + "`n")

# ---- .sdlc/service.json: the durable link record ----
$projectRootRel = (Get-RelPath $serviceDir $root) -replace '/+$', ''
if ($govFolders.Count) {
  $gfJson = "[`n" + (($govFolders | ForEach-Object { '    "' + (Get-JsonEsc $_) + '"' }) -join ",`n") + "`n  ]"
} else { $gfJson = '[]' }
$serviceJson = @"
{
  "schema": 1,
  "project": "$(Get-JsonEsc $info.project)",
  "service": "$(Get-JsonEsc $name)",
  "type": "$(Get-JsonEsc $type)",
  "frameworkPlugin": "$PLUGIN",
  "frameworkPin": "$(Get-JsonEsc $frameworkPin)",
  "projectRootRel": "$(Get-JsonEsc $projectRootRel)",
  "governanceFolders": $gfJson
}
"@
Write-Utf8 (Join-Path $serviceDir '.sdlc/service.json') ($serviceJson + "`n")

# ---- best-effort plugin registration/install via the claude CLI ----
$marketplace = Get-RelPath $serviceDir (Join-Path $root '.claude-plugin/marketplace.json')
$claudeOk = $null -ne (Get-Command claude -ErrorAction SilentlyContinue)
if ($claudeOk) {
  if ($cmd -eq 'sync') { Invoke-Best "claude plugin marketplace update $MARKETPLACE" }
  else { Invoke-Best "claude plugin marketplace add $marketplace" }
  if ($cmd -eq 'sync') { Invoke-Best "claude plugin update $PLUGIN --scope user --yes" }
  else { Invoke-Best "claude plugin install $PLUGIN --scope user --yes" }
}

# ---- summary ----
$verb = if ($cmd -eq 'sync') { 'Synced' } else { 'Wired' }
Write-Host ""
Write-Host "OK $verb service `"$name`" ($type) to project $($info.project)"
Write-Host "  - CLAUDE.md            $EMDASH $($govImports.Count) governance file(s) + $($artImports.Count) artifact(s) imported"
Write-Host "  - .claude/settings.json $EMDASH sdlc plugin enabled"
Write-Host "  - .sdlc/service.json    $EMDASH link record written"
if (-not $claudeOk) {
  Write-Host ""
  Write-Host "  The ``claude`` CLI was not found, so the framework plugin was not installed automatically."
  Write-Host "  Once Claude Code is installed, run from this folder:"
  Write-Host "    claude plugin marketplace add $marketplace"
  Write-Host "    claude plugin install $PLUGIN --scope user --yes"
}
Write-Host ""
Write-Host "  Next: open Claude Code here and run ``/init`` to complete the service overview."
Write-Host ""
exit 0
